// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StudentGrades.Dal;
using System;

namespace StudentGrades.Migrations
{
    [DbContext(typeof(StudentGradesContext))]
    [Migration("20171106220823_CreateTablesRestrictions")]
    partial class CreateTablesRestrictions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("StudentGrades.Models.Grade", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnName("studentid");

                    b.Property<string>("Subject")
                        .HasColumnName("subject");

                    b.Property<int>("GradeNumber")
                        .HasColumnName("gradenumber");

                    b.HasKey("StudentId", "Subject");

                    b.ToTable("grade");
                });

            modelBuilder.Entity("StudentGrades.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("StudentGrades.Models.Grade", b =>
                {
                    b.HasOne("StudentGrades.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
